version: 1.0.{build}
os: Visual Studio 2015
skip_tags: true
configuration: Release
environment:
 nodejs_version: "0.12"
 COVERALLS_REPO_TOKEN:
   secure: oI8JLO5/25+ZMrrWdVckNz5zqUysVlU+VVMBpPxZlEXaQ/A/6z544OcIs8rVhk49
cache:
- "%LOCALAPPDATA%\\Yarn"
install:
- npm i -g yarn
- npm i -g typescript typings
- yarn global add typescript typings
- cd ".\Promact.Oauth.Server\src\Promact.Oauth.Server\"
- yarn
- cd..
build_script:
- ps: dotnet restore
build:
  project: .\Promact.Oauth.Server\Promact.Oauth.Server.sln
  verbosity: minimal
test_script:
- ps: >-
   C:\Users\appveyor\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test -f netcoreapp1.1 -c Release Promact.Oauth.Server.Tests" -filter:"+[Promact.Oauth.Server]*Repository" -mergeoutput -hideskipped:File -output:opencover.xml -oldStyle

   if(![string]::IsNullOrEmpty($env:COVERALLS_REPO_TOKEN)){

   $coveralls = (Resolve-Path "C:\Users\appveyor\.nuget\packages\coveralls.net\0.8.0-unstable0013\tools\csmacnz.coveralls.exe").ToString()

   & $coveralls --opencover -i opencover.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
   }   